version: '3.8'

services:
  # RabbitMQ service
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: donation-platform-rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management interface port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - donation-platform-network

  # Message broker service
  message-broker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: donation-platform-message-broker
    environment:
      - NODE_ENV=development
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - LOG_LEVEL=debug
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - donation-platform-network

# Define persistent volumes
volumes:
  rabbitmq_data:
  rabbitmq_logs:

# Define network
networks:
  donation-platform-network:
    driver: bridge