scrape_configs:
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['host.docker.internal:15692']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['host.docker.internal:3001']
